Output demo2.gif

Set FontSize 20
Set Width 1920
Set Height 1080
Set TypingSpeed 400ms

Set Shell zsh
Sleep 1.5s
Type "entab"
Tab
Sleep 500ms
Type "-lf"
Enter
Sleep 2.5s
Type "j"
Sleep 4s
Enter
Sleep 5.5s
Type "jjj"
Sleep 500ms
Type@50ms "jj"
Sleep 500ms
Type@50ms "jjjjjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkk/"
Sleep 2s
Type "MUN"
Sleep 1s
Escape
Sleep 500ms
Enter
Sleep 1.5s
Type "kjkd"
Sleep 1.5s
Type "j j "
Sleep 1s
Enter
Sleep 1s
Type "q"
Sleep 3.5s
