Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 16
Set Width 1920
Set Height 1080

Set Shell zsh
Sleep 2.5s
Type "cargo run"
Sleep 3s
Enter
Sleep 5s
Type "jjk"
Sleep 3s
Enter
Sleep 3s
Type "/"
Sleep 3s
Type "half"
Sleep 4s
Escape
Type "jk"
Enter
Sleep 4s
Type "kk"
Sleep 6s
Escape
Sleep 3s
Escape
Type "j"
Enter
Sleep 2.5s
Type "jjjjjjjjjjjjjjjjjjjjjjjjjkjj"
Sleep 2.5s
Enter
Sleep 3.5s
Type "kjjk"
Sleep 4.5s
Escape
Sleep 4.5s
Type "q"
Sleep 3s
